## Data Cleanin in Pandas

In [2]:
import pandas as pd

In [3]:
df = pd.read_excel(r'C:\Users\PRAISE\Downloads\Customer Call List.xlsx')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [10]:
df.at[15,'Last_Name']

'Weasley'

In [15]:
df.first_valid_index()

0

In [104]:
#removing duplicates
df = df.drop_duplicates()

In [105]:
#removing unwanted columns
df.drop(columns ='Not_Useful_Column', inplace = True )

C:\Users\PRAISE\AppData\Local\Temp\ipykernel_10304\1162206289.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns ='Not_Useful_Column', inplace = True )

In [106]:
#removing unwanted signs using strip/lstrip/rstrip
#df['Last_Name'] = df['Last_Name'].str.lstrip('...')
#df['Last_Name']=df['Last_Name'].str.lstrip('/')
#df['Last_Name']=df['Last_Name'].str.rstrip('_')
df['Last_Name'] = df['Last_Name'].str.strip('123./_')
df

C:\Users\PRAISE\AppData\Local\Temp\ipykernel_10304\1460478336.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Last_Name'] = df['Last_Name'].str.strip('123./_')

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [86]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [107]:
df['Phone_Number']=df['Phone_Number'].str.replace('[^a-zA-Z0-9]','')
df

C:\Users\PRAISE\AppData\Local\Temp\ipykernel_10304\430231681.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Phone_Number']=df['Phone_Number'].str.replace('[^a-zA-Z0-9]','')
C:\Users\PRAISE\AppData\Local\Temp\ipykernel_10304\430231681.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Phone_Number']=df['Phone_Number'].str.replace('[^a-zA-Z0-9]','')

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,1236439775,93 West Main Street,No,Yes
2,1003,Walter,White,NaN,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,3047622467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,Na,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,NaN,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,1235432345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,8766783469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,N,No
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,NaN,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,Na,N/a,N/a,Yes
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Yes,N

In [109]:
#df['Phone_Number'].apply(lambda x: x[0:3]+ '-' + x[3:6] + '-' + x[6:10])
#this is the main step, but because the phone_number column contains str it will not work

#hence we yurn it into a str first
#df['Phone_Number']= df['Phone_Number'].apply(lambda x: str(x))

#then run the main step again
#df['Phone_Number'] = df['Phone_Number'].apply(lambda x: x[0:3]+ '-' + x[3:6] + '-' + x[6:10])

#then remove the unwanted string values
df['Phone_Number'] = df['Phone_Number'].str.replace('nan--', '')
df['Phone_Number'] = df['Phone_Number'].str.replace('Na--','')

df

C:\Users\PRAISE\AppData\Local\Temp\ipykernel_10304\4263293472.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Phone_Number'] = df['Phone_Number'].str.replace('nan--', '')
C:\Users\PRAISE\AppData\Local\Temp\ipykernel_10304\4263293472.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Phone_Number'] = df['Phone_Number'].str.replace('Na--','')

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes
2,1003,Walter,White,,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,,1209 South Street,No,No
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N

In [169]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes
2,1003,Walter,White,,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,,1209 South Street,No,No
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N

In [174]:
df[['Street_address', 'State', 'Zip_Code']] = df['Address'].str.split(',',2, expand= True)
df

C:\Users\PRAISE\AppData\Local\Temp\ipykernel_10304\1426142964.py:1: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  df[['Street_address', 'State', 'Zip_Code']] = df['Address'].str.split(',',2, expand= True)
C:\Users\PRAISE\AppData\Local\Temp\ipykernel_10304\1426142964.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['Street_address', 'State', 'Zip_Code']] = df['Address'].str.split(',',2, expand= True)
C:\Users\PRAISE\AppData\Local\Temp\ipykernel_10304\1426142964.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['Street_address', 'State', 'Zip_Code']] = df['Address'].str.split(',',2, expand= True)
C:\Users\PRAISE\AppData\Local\Temp\ipykernel_10304\1426142964.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['Street_address', 'State', 'Zip_Code']] = df['Address'].str.split(',',2, expand= True)

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,93 West Main Street,None,None
2,1003,Walter,White,,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,,1209 South Street,No,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,612 Shire Lane,Shire,None
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,N/a,Yes,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine,None

In [183]:
df['Paying Customer'] = df['Paying Customer'].str.replace ('Yes', 'Y')
df['Paying Customer'] = df['Paying Customer'].str.replace ('No', 'N')
df['Do_Not_Contact'] = df['Do_Not_Contact'].str.replace ('No', 'N')
df['Do_Not_Contact'] = df['Do_Not_Contact'].str.replace ('Yes', 'Y')
df

C:\Users\PRAISE\AppData\Local\Temp\ipykernel_10304\2499248545.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Paying Customer'] = df['Paying Customer'].str.replace ('Yes', 'Y')
C:\Users\PRAISE\AppData\Local\Temp\ipykernel_10304\2499248545.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Paying Customer'] = df['Paying Customer'].str.replace ('No', 'N')
C:\Users\PRAISE\AppData\Local\Temp\ipykernel_10304\2499248545.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Do_Not_Contact'] = df['Do_Not_Contact'].str.replace ('No', 'N')
C:\Users\PRAISE\AppData\Local\Temp\ipykernel_10304\2499248545.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Do_Not_Contact'] = df['Do_Not_Contact'].str.replace ('Yes', 'Y')

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Y,93 West Main Street,None,None
2,1003,Walter,White,,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,768 City Parkway,None,None
6,1007,Jeff,Winger,,1209 South Street,N,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,123 Middle Earth,Y,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,None
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,N/a,Y,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,None

In [189]:
df = df.replace('N/a','')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Y,93 West Main Street,None,None
2,1003,Walter,White,,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,768 City Parkway,None,None
6,1007,Jeff,Winger,,1209 South Street,N,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,123 Middle Earth,Y,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,None
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,,,Y,,None,None
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,None

In [192]:
df=df.fillna('')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Y,93 West Main Street,,
2,1003,Walter,White,,298 Drugs Driveway,N,,298 Drugs Driveway,,
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,,
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,768 City Parkway,,
6,1007,Jeff,Winger,,1209 South Street,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,,
8,1009,Gandalf,,,123 Middle Earth,Y,,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,,3498 Super Lane,Y,,3498 Super Lane,,
18,1019,Creed,Braton,,,,Y,,,
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

In [204]:
for x in df.index:
    if df.loc[x,'Do_Not_Contact'] =='Y':
        df.drop(x, inplace = True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
2,1003,Walter,White,,298 Drugs Driveway,N,,298 Drugs Driveway,,
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,,
6,1007,Jeff,Winger,,1209 South Street,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,,
8,1009,Gandalf,,,123 Middle Earth,Y,,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,,3498 Super Lane,Y,,3498 Super Lane,,
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

In [218]:
for x in df.index:
    if df.loc[x,'Phone_Number'] == '':
        df.drop(x, inplace = True)
    
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,,
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,,
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

In [222]:
df.reset_index(drop = True)

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
1,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,,
2,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,,
3,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,
4,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,,
5,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,,
6,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,,
7,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
8,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
9,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

In [180]:
ig1.fillna('')

,Date,Post ID,Network,Post Type,Profile,Sent by,Link,Post,Linked Content,Impressions,...,Video Removed from Playlists,Annotation Impressions,Annotation Clickable Impressions,Annotation Closable Impressions,Annotation Closes,Card Impressions,Card Teaser Impressions,Card Teaser Clicks,Poll Votes,Tags
Content Type,,,,,,,,,,,,,,,,,,,,,
Carousel,1/30/2023 5:06 pm,18216468940204235,Instagram,Post,stanbicibtc,,https://www.instagram.com/p/CoC6CKBIHbV/,The new Naira banknotes in circulation have se...,,"39,681",...,,,,,,,,,,
Photo,4/15/2022 9:04 am,17971531720518163,Instagram,Post,stanbicibtc,Blessing Ubah,https://www.instagram.com/p/CcXUQTEMRm7/,We hope the faith that this #GoodFriday restor...,,"29,186",...,,,,,,,,,,
Video,5/28/2021 8:45 pm,18008486986321009,Instagram,Post,stanbicibtc,,https://www.instagram.com/p/CPbcdjygiaK/,Reposted from @mzdosunmu My son's entry\n#ITCA...,,"21,175",...,,,,,,,,,,
Carousel,1/4/2023 4:08 pm,17903404469640387,Instagram,Post,stanbicibtc,,https://www.instagram.com/p/Cm_2oino-Me/,The new Naira banknotes in circulation have se...,,"23,425",...,,,,,,,,,,
Photo,12/7/2021 6:52 pm,17950858072558814,Instagram,Post,stanbicibtc,Blessing Ubah,https://www.instagram.com/p/CXMNAKFsjSs/,"If you were born in June, ‘cut soap for us oh’...",,"21,033",...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Photo,12/24/2014 5:37 pm,17841808444024797,Instagram,Post,stanbicibtc,,https://www.instagram.com/p/w_xUG5yvRB/,"Withdraw cash up to 5 times, pay bills or tran...",,,...,,,,,,,,,,
Photo,12/24/2014 10:28 am,17841674617024797,Instagram,Post,stanbicibtc,,https://www.instagram.com/p/w_AUutyvQD/,#CardDiaries week 13\n\nI love Christmas! In m...,,,...,,,,,,,,,,
Photo,12/23/2014 5:14 pm,17842896850024797,Instagram,Post,stanbicibtc,,https://www.instagram.com/p/w9J5vpyvY4/,Eat-in this holidays. \nInstead of going out t...,,,...,,,,,,,,,,
Photo,12/23/2014 10:38 am,17841674620024797,Instagram,Post,stanbicibtc,,https://www.instagram.com/p/w8cnwpSvY5/,"If you do not move forward, you will always be...",,,...,,,,,,,,,,
Photo,12/22/2014 5:59 pm,17841808438024797,Instagram,Post,stanbicibtc,,https://www.instagram.com/p/w6qRb-yvai/,Travel to Dubai this season with #StanbicDelig...,,,...,,,,,,,,,,

In [1]:
import pandas as pd

In [28]:
ig1=pd.read_csv(r'C:\Users\PRAISE\Downloads\January1 - July 13_ 2023_Instagram.csv', low_memory= False)

In [29]:
ig1 = ig1.drop_duplicates()

In [30]:
ig1[['Date','Time']] = ig1['Date'].str.split(' ',1, expand= True) 
ig1

C:\Users\PRAISE\AppData\Local\Temp\ipykernel_11108\2929621368.py:1: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  ig1[['Date','Time']] = ig1['Date'].str.split(' ',1, expand= True)

,Date,Post ID,Network,Post Type,Content Type,Profile,Sent by,Link,Post,Linked Content,Impressions,Organic Impressions,Viral Impressions,Non-viral Impressions,Paid Impressions,Fan Impressions,Fan Organic Impressions,Fan Paid Impressions,Non-fan Impressions,Non-fan Organic Impressions,Non-fan Paid Impressions,Reach,Organic Reach,Viral Reach,Non-viral Reach,Paid Reach,Fan Reach,Fan Paid Reach,Potential Reach,Engagement Rate (per Impression),Engagement Rate (per Reach),Engagements,Reactions,Likes,Dislikes,Love Reactions,Haha Reactions,Wow Reactions,Sad Reactions,Angry Reactions,Comments,Shares,Saves,Click-Through Rate,Post Link Clicks,Other Post Clicks,Post Clicks (All),Post Media Clicks,Post Hashtag Clicks,Post Detail Expand Clicks,Profile Clicks,Post Photo View Clicks,Post Video Play Clicks,Other Engagements,Answers,App Engagements,App Install Attempts,App Opens,Follows from Post,Unfollows from Post,Negative Feedback,bit.ly Link Clicks,Engaged Users,Engaged Fans,Users Talking About This,Unique Reactions,Unique Comments,Unique Shares,Unique Answers,Unique Post Clicks,Unique Post Link Clicks,Unique Post Photo View Clicks,Unique Post Video Play Clicks,Unique Other Post Clicks,Unique Negative Feedback,Subscribers Gained from Video,Annotation Clicks,Card Clicks,Video Views,Media Views,Organic Video Views,Paid Video Views,Partial Video Views,Organic Partial Video Views,Paid Partial Video Views,Full Video Views,Full Video View Rate,Follow Video Views,For You Video Views,Hashtag Video Views,Business Account Video Views,Sound Video Views,Unspecified Video Views,Organic Full Video Views,Paid Full Video Views,Autoplay Video Views,Click to Play Video Views,Sound on Video Views,Sound off Video Views,10-Second Video Views,Organic 10-Second Video Views,Paid 10-Second Video Views,Autoplay 10-Second Video Views,Click to Play 10-Second Video Views,Sound on 10-Second Video Views,Sound off 10-Second Video Views,Autoplay Partial Video Views,Click to Play Partial Video Views,Autoplay Full Video Views,Click to Play Full Video Views,95% Video Views,Organic 95% Video Views,Paid 95% Video Views,Video Length (Seconds),Average Video Time Watched (Seconds),Video View Time (Seconds),Organic Video View Time (Seconds),Paid Video View Time (Seconds),Unique Video Views,Unique Organic Video Views,Unique Paid Video Views,Unique 10-Second Video Views,Unique Full Video Views,Unique Organic 95% Video Views,Unique Paid 95% Video Views,Video Ad Break Ad Impressions,Video Ad Break Ad Earnings,Video Ad Break Ad Cost per Impression (CPM),YouTube Premium Views,Estimated Minutes Watched,Estimated Premium Minutes Watched,Story Taps Back,Story Taps Forward,Story Exits,Story Replies,Video Added to Playlists,Subscribers Lost from Video,Video Removed from Playlists,Annotation Impressions,Annotation Clickable Impressions,Annotation Closable Impressions,Annotation Closes,Card Impressions,Card Teaser Impressions,Card Teaser Clicks,Poll Votes,Tags,Time
0,1/30/2023,18216468940204235,Instagram,Post,Carousel,stanbicibtc,,https://www.instagram.com/p/CoC6CKBIHbV/,The new Naira banknotes in circulation have se...,NaN,"39,681","39,681",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"32,418","32,418",NaN,NaN,NaN,NaN,NaN,NaN,4.89%,5.99%,"1,942","1,261","1,261",NaN,NaN,NaN,NaN,NaN,NaN,56,NaN,625.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5:06 pm
1,4/15/2022,17971531720518163,Instagram,Post,Photo,stanbicibtc,Blessing Ubah,https://www.instagram.com/p/CcXUQTEMRm7/,We hope the faith that this #GoodFriday restor...,NaN,"29,186","29,186",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"25,055","25,055",NaN,NaN,NaN,NaN,NaN,NaN,6.04%,7.04%,"1,763",709,709,NaN,NaN,NaN,NaN,NaN,NaN,"1,033",NaN,21.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9:04 am
2,5/28/2021,18008486986321009,Instagram,Post,Video,stanbicibtc,,https://www.instagram.com/p/CPbcdjygiaK/,Reposted from @mzdosunmu My son's entry\n#ITCA...,NaN,"21,175","21,175",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"19,237","19,237",NaN,NaN,NaN,NaN,NaN,NaN,3.48%,3.83%,736,702,702,NaN,NaN,NaN,NaN,NaN,NaN,23,NaN,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"10,392",NaN,"10,392",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8:45 pm
3,1/4/2023,17903404469640387,Instagram,Post,Carousel,stanbicibtc,,https://www.instagram.com/p/Cm_2oino-Me/,The new Naira banknotes in circulation have se...,NaN,"23,425","23,425",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"18,993","18,993",NaN,NaN,NaN,NaN,NaN,NaN,4.48%,5.53%,"1,050",677,677,NaN,NaN,NaN,NaN,NaN,NaN,36,NaN,337.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4:08 pm
4,12/7/2021,17950858072558814,Instagram,Post,Photo,stanbicibtc,Blessing Ubah,https://www.instagram.com/p/CXMNAKFsjSs/,"If you were born in June, ‘cut soap for us oh’...",NaN,"21,033","21,033",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"18,335","18,335",NaN,NaN,NaN,NaN,NaN,NaN,6.58%,7.54%,"1,383",757,757,NaN,NaN,NaN,NaN,NaN,NaN,606,NaN,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6:52 pm
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,12/24/2014,17841808444024797,Instagram,Post,Photo,stanbicibtc,,https://www.instagram.com/p/w_xUG5yvRB/,"Withdraw cash up to 5 times, pay bills or tran...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,6,6,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5:37 pm
9996,12/24/2014,17841674617024797,Instagram,Post,Photo,stanbicibtc,,https://www.instagram.com/p/w_AUutyvQD/,#CardDiaries week 13\n\nI love Christmas! In m...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,6,6,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10:28 am
9997,12/23/2014,17842896850024797,Instagram,Post,Photo,stanbicibtc,,https://www.instagram.com/p/w9J5vpyvY4/,Eat-in this holidays. \nInstead of going out t...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,6,6,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5:14 pm
9998,12/23/2014,17841674620024797,Instagram,Post,Photo,stanbicibtc,,https://www.instagram.com/p/w8cnwpSvY5/,"If you do not move forward, you will always be...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,7,7,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10:38 am
9999,12/22/2014,17841808438024797,Instagram,Post,Photo,stanbicibtc,,https://www.instagram.com/p/w6qRb-yvai/,Travel to Dubai this season with #StanbicDelig...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,7,7,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5:59 pm

In [1]:
pd.set_option('display.max.columns',150)
pd.set_option('display.max.rows', 100)

KeyboardInterrupt

In [52]:
#ig1 = ig1.fillna('')
ig1

,Content Type,Date,Post ID,Network,Post Type,Profile,Sent by,Link,Post,Linked Content,Impressions,Organic Impressions,Viral Impressions,Non-viral Impressions,Paid Impressions,Fan Impressions,Fan Organic Impressions,Fan Paid Impressions,Non-fan Impressions,Non-fan Organic Impressions,Non-fan Paid Impressions,Reach,Organic Reach,Viral Reach,Non-viral Reach,Paid Reach,Fan Reach,Fan Paid Reach,Potential Reach,Engagement Rate (per Impression),Engagement Rate (per Reach),Engagements,Reactions,Likes,Dislikes,Love Reactions,Haha Reactions,Wow Reactions,Sad Reactions,Angry Reactions,Comments,Shares,Saves,Click-Through Rate,Post Link Clicks,Other Post Clicks,Post Clicks (All),Post Media Clicks,Post Hashtag Clicks,Post Detail Expand Clicks,Profile Clicks,Post Photo View Clicks,Post Video Play Clicks,Other Engagements,Answers,App Engagements,App Install Attempts,App Opens,Follows from Post,Unfollows from Post,Negative Feedback,bit.ly Link Clicks,Engaged Users,Engaged Fans,Users Talking About This,Unique Reactions,Unique Comments,Unique Shares,Unique Answers,Unique Post Clicks,Unique Post Link Clicks,Unique Post Photo View Clicks,Unique Post Video Play Clicks,Unique Other Post Clicks,Unique Negative Feedback,Subscribers Gained from Video,Annotation Clicks,Card Clicks,Video Views,Media Views,Organic Video Views,Paid Video Views,Partial Video Views,Organic Partial Video Views,Paid Partial Video Views,Full Video Views,Full Video View Rate,Follow Video Views,For You Video Views,Hashtag Video Views,Business Account Video Views,Sound Video Views,Unspecified Video Views,Organic Full Video Views,Paid Full Video Views,Autoplay Video Views,Click to Play Video Views,Sound on Video Views,Sound off Video Views,10-Second Video Views,Organic 10-Second Video Views,Paid 10-Second Video Views,Autoplay 10-Second Video Views,Click to Play 10-Second Video Views,Sound on 10-Second Video Views,Sound off 10-Second Video Views,Autoplay Partial Video Views,Click to Play Partial Video Views,Autoplay Full Video Views,Click to Play Full Video Views,95% Video Views,Organic 95% Video Views,Paid 95% Video Views,Video Length (Seconds),Average Video Time Watched (Seconds),Video View Time (Seconds),Organic Video View Time (Seconds),Paid Video View Time (Seconds),Unique Video Views,Unique Organic Video Views,Unique Paid Video Views,Unique 10-Second Video Views,Unique Full Video Views,Unique Organic 95% Video Views,Unique Paid 95% Video Views,Video Ad Break Ad Impressions,Video Ad Break Ad Earnings,Video Ad Break Ad Cost per Impression (CPM),YouTube Premium Views,Estimated Minutes Watched,Estimated Premium Minutes Watched,Story Taps Back,Story Taps Forward,Story Exits,Story Replies,Video Added to Playlists,Subscribers Lost from Video,Video Removed from Playlists,Annotation Impressions,Annotation Clickable Impressions,Annotation Closable Impressions,Annotation Closes,Card Impressions,Card Teaser Impressions,Card Teaser Clicks,Poll Votes,Tags,Time
0,Carousel,1/30/2023,18216468940204235,Instagram,Post,stanbicibtc,,https://www.instagram.com/p/CoC6CKBIHbV/,The new Naira banknotes in circulation have se...,,"39,681","39,681",,,,,,,,,,"32,418","32,418",,,,,,,4.89%,5.99%,"1,942","1,261","1,261",,,,,,,56,,625.0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,0,,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,5:06 pm
1,Photo,4/15/2022,17971531720518163,Instagram,Post,stanbicibtc,Blessing Ubah,https://www.instagram.com/p/CcXUQTEMRm7/,We hope the faith that this #GoodFriday restor...,,"29,186","29,186",,,,,,,,,,"25,055","25,055",,,,,,,6.04%,7.04%,"1,763",709,709,,,,,,,"1,033",,21.0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,9:04 am
2,Video,5/28/2021,18008486986321009,Instagram,Post,stanbicibtc,,https://www.instagram.com/p/CPbcdjygiaK/,Reposted from @mzdosunmu My son's entry\n#ITCA...,,"21,175","21,175",,,,,,,,,,"19,237","19,237",,,,,,,3.48%,3.83%,736,702,702,,,,,,,23,,11.0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,"10,392",,"10,392",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,8:45 pm
3,Carousel,1/4/2023,17903404469640387,Instagram,Post,stanbicibtc,,https://www.instagram.com/p/Cm_2oino-Me/,The new Naira banknotes in circulation have se...,,"23,425","23,425",,,,,,,,,,"18,993","18,993",,,,,,,4.48%,5.53%,"1,050",677,677,,,,,,,36,,337.0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,0,,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,4:08 pm
4,Photo,12/7/2021,17950858072558814,Instagram,Post,stanbicibtc,Blessing Ubah,https://www.instagram.com/p/CXMNAKFsjSs/,"If you were born in June, ‘cut soap for us oh’...",,"21,033","21,033",,,,,,,,,,"18,335","18,335",,,,,,,6.58%,7.54%,"1,383",757,757,,,,,,,606,,20.0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,6:52 pm
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Photo,12/24/2014,17841808444024797,Instagram,Post,stanbicibtc,,https://www.instagram.com/p/w_xUG5yvRB/,"Withdraw cash up to 5 times, pay bills or tran...",,,,,,,,,,,,,,,,,,,,,,,6,6,6,,,,,,,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,5:37 pm
9996,Photo,12/24/2014,17841674617024797,Instagram,Post,stanbicibtc,,https://www.instagram.com/p/w_AUutyvQD/,#CardDiaries week 13\n\nI love Christmas! In m...,,,,,,,,,,,,,,,,,,,,,,,6,6,6,,,,,,,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,10:28 am
9997,Photo,12/23/2014,17842896850024797,Instagram,Post,stanbicibtc,,https://www.instagram.com/p/w9J5vpyvY4/,Eat-in this holidays. \nInstead of going out t...,,,,,,,,,,,,,,,,,,,,,,,6,6,6,,,,,,,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,5:14 pm
9998,Photo,12/23/2014,17841674620024797,Instagram,Post,stanbicibtc,,https://www.instagram.com/p/w8cnwpSvY5/,"If you do not move forward, you will always be...",,,,,,,,,,,,,,,,,,,,,,,7,7,7,,,,,,,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,10:38 am
9999,Photo,12/22/2014,17841808438024797,Instagram,Post,stanbicibtc,,https://www.instagram.com/p/w6qRb-yvai/,Travel to Dubai this season with #StanbicDelig...,,,,,,,,,,,,,,,,,,,,,,,7,7,7,,,,,,,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,5:59 pm

In [70]:
#ig = ig1.set_index(['Content Type', 'Date'])
ig.sort_index()
#ig =ig.reset_index()
ig

                                   Post ID    Network Post Type      Profile  \
Content Type Date
Carousel     1/30/2023   18216468940204235  Instagram      Post  stanbicibtc
Photo        4/15/2022   17971531720518163  Instagram      Post  stanbicibtc
Video        5/28/2021   18008486986321009  Instagram      Post  stanbicibtc
Carousel     1/4/2023    17903404469640387  Instagram      Post  stanbicibtc
Photo        12/7/2021   17950858072558814  Instagram      Post  stanbicibtc
...                                    ...        ...       ...          ...
             12/24/2014  17841808444024797  Instagram      Post  stanbicibtc
             12/24/2014  17841674617024797  Instagram      Post  stanbicibtc
             12/23/2014  17842896850024797  Instagram      Post  stanbicibtc
             12/23/2014  17841674620024797  Instagram      Post  stanbicibtc
             12/22/2014  17841808438024797  Instagram      Post  stanbicibtc

                               Sent by  \
Content Type Date
Carousel     1/30/2023
Photo        4/15/2022   Blessing Ubah
Video        5/28/2021
Carousel     1/4/2023
Photo        12/7/2021   Blessing Ubah
...                                ...
             12/24/2014
             12/24/2014
             12/23/2014
             12/23/2014
             12/22/2014

                                                             Link  \
Content Type Date
Carousel     1/30/2023   https://www.instagram.com/p/CoC6CKBIHbV/
Photo        4/15/2022   https://www.instagram.com/p/CcXUQTEMRm7/
Video        5/28/2021   https://www.instagram.com/p/CPbcdjygiaK/
Carousel     1/4/2023    https://www.instagram.com/p/Cm_2oino-Me/
Photo        12/7/2021   https://www.instagram.com/p/CXMNAKFsjSs/
...                                                           ...
             12/24/2014   https://www.instagram.com/p/w_xUG5yvRB/
             12/24/2014   https://www.instagram.com/p/w_AUutyvQD/
             12/23/2014   https://www.instagram.com/p/w9J5vpyvY4/
             12/23/2014   https://www.instagram.com/p/w8cnwpSvY5/
             12/22/2014   https://www.instagram.com/p/w6qRb-yvai/

                                                                      Post  \
Content Type Date
Carousel     1/30/2023   The new Naira banknotes in circulation have se...
Photo        4/15/2022   We hope the faith that this #GoodFriday restor...
Video        5/28/2021   Reposted from @mzdosunmu My son's entry\n#ITCA...
Carousel     1/4/2023    The new Naira banknotes in circulation have se...
Photo        12/7/2021   If you were born in June, ‘cut soap for us oh’...
...                                                                    ...
             12/24/2014  Withdraw cash up to 5 times, pay bills or tran...
             12/24/2014  #CardDiaries week 13\n\nI love Christmas! In m...
             12/23/2014  Eat-in this holidays. \nInstead of going out t...
             12/23/2014  If you do not move forward, you will always be...
             12/22/2014  Travel to Dubai this season with #StanbicDelig...

                        Linked Content Impressions Organic Impressions  \
Content Type Date
Carousel     1/30/2023                      39,681              39,681
Photo        4/15/2022                      29,186              29,186
Video        5/28/2021                      21,175              21,175
Carousel     1/4/2023                       23,425              23,425
Photo        12/7/2021                      21,033              21,033
...                                ...         ...                 ...
             12/24/2014
             12/24/2014
             12/23/2014
             12/23/2014
             12/22/2014

                        Viral Impressions Non-viral Impressions  \
Content Type Date
Carousel     1/30/2023
Photo        4/15/2022
Video        5/28/2021
Carousel     1/4/2023
Photo        12/7/2021
...                                   ...                   ...
             12/24/2014
             12/24/2014
             12/23/2014
             12/23/2014
             12/22/2014

                        Paid Impressions Fan Impressions  \
Content Type Date
Carousel     1/30/2023
Photo        4/15/2022
Video        5/28/2021
Carousel     1/4/2023
Photo        12/7/2021
...                                  ...             ...
             12/24/2014
             12/24/2014
             12/23/2014
             12/23/2014
             12/22/2014

                        Fan Organic Impressions Fan Paid Impressions  \
Content Type Date
Carousel     1/30/2023
Photo        4/15/2022
Video        5/28/2021
Carousel     1/4/2023
Photo        12/7/2021
...                                         ...                  ...
             12/24/2014
             12/24/2014
             12/23/2014
             12/23/2014
             12/22/2014

                        Non-fan Impressions Non-fan Organic Impressions  \
Content Type Date
Carousel     1/30/2023
Photo        4/15/2022
Video        5/28/2021
Carousel     1/4/2023
Photo        12/7/2021
...                                     ...                         ...
             12/24/2014
             12/24/2014
             12/23/2014
             12/23/2014
             12/22/2014

                        Non-fan Paid Impressions   Reach Organic Reach  \
Content Type Date
Carousel     1/30/2023                            32,418        32,418
Photo        4/15/2022                            25,055        25,055
Video        5/28/2021                            19,237        19,237
Carousel     1/4/2023                             18,993        18,993
Photo        12/7/2021                            18,335        18,335
...                                          ...     ...           ...
             12/24/2014
             12/24/2014
             12/23/2014
             12/23/2014
             12/22/2014

                        Viral Reach Non-viral Reach Paid Reach Fan Reach  \
Content Type Date
Carousel     1/30/2023
Photo        4/15/2022
Video        5/28/2021
Carousel     1/4/2023
Photo        12/7/2021
...                             ...             ...        ...       ...
             12/24/2014
             12/24/2014
             12/23/2014
             12/23/2014
             12/22/2014

                        Fan Paid Reach Potential Reach  \
Content Type Date
Carousel     1/30/2023
Photo        4/15/2022
Video        5/28/2021
Carousel     1/4/2023
Photo        12/7/2021
...                                ...             ...
             12/24/2014
             12/24/2014
             12/23/2014
             12/23/2014
             12/22/2014

                        Engagement Rate (per Impression)  \
Content Type Date
Carousel     1/30/2023                             4.89%
Photo        4/15/2022                             6.04%
Video        5/28/2021                             3.48%
Carousel     1/4/2023                              4.48%
Photo        12/7/2021                             6.58%
...                                                  ...
             12/24/2014
             12/24/2014
             12/23/2014
             12/23/2014
             12/22/2014

                        Engagement Rate (per Reach) Engagements Reactions  \
Content Type Date
Carousel     1/30/2023                        5.99%       1,942     1,261
Photo        4/15/2022                        7.04%       1,763       709
Video        5/28/2021                        3.83%         736       702
Carousel     1/4/2023                         5.53%       1,050       677
Photo        12/7/2021                        7.54%       1,383       757
...                                             ...         ...       ...
             12/24/2014                                       6         6
             12/24/2014                                       6         6
             12/23/2014                                       6         6
             12/23/2014                                       7         7
             12/22/2014                                       7         7

                         Likes Dislikes Love Reactions Haha Reactions  \
Content Type Date
Carousel     1/30/2023   1,261
Photo        4/15/2022     709
Video        5/28/2021     702
Carousel     1/4/2023      677
Photo        12/7/2021     757
...                        ...      ...            ...            ...
             12/24/2014      6
             12/24/2014      6
             12/23/2014      6
             12/23/2014      7
             12/22/2014      7

                        Wow Reactions Sad Reactions Angry Reactions Comments  \
Content Type Date
Carousel     1/30/2023                                                    56
Photo        4/15/2022                                                 1,033
Video        5/28/2021                                                    23
Carousel     1/4/2023                                                     36
Photo        12/7/2021                                                   606
...                               ...           ...             ...      ...
             12/24/2014                                                    0
             12/24/2014                                                    0
             12/23/2014                                                    0
             12/23/2014                                                    0
             12/22/2014                                                    0

                        Shares  Saves Click-Through Rate Post Link Clicks  \
Content Type Date
Carousel     1/30/2023          625.0
Photo        4/15/2022           21.0
Video        5/28/2021           11.0
Carousel     1/4/2023           337.0
Photo        12/7/2021           20.0
...                        ...    ...                ...              ...
             12/24/2014
             12/24/2014
             12/23/2014
             12/23/2014
             12/22/2014

                        Other Post Clicks Post Clicks (All) Post Media Clicks  \
Content Type Date
Carousel     1/30/2023
Photo        4/15/2022
Video        5/28/2021
Carousel     1/4/2023
Photo        12/7/2021
...                                   ...               ...               ...
             12/24/2014
             12/24/2014
             12/23/2014
             12/23/2014
             12/22/2014

                        Post Hashtag Clicks Post Detail Expand Clicks  \
Content Type Date
Carousel     1/30/2023
Photo        4/15/2022
Video        5/28/2021
Carousel     1/4/2023
Photo        12/7/2021
...                                     ...                       ...
             12/24/2014
             12/24/2014
             12/23/2014
             12/23/2014
             12/22/2014

                        Profile Clicks Post Photo View Clicks  \
Content Type Date
Carousel     1/30/2023
Photo        4/15/2022
Video        5/28/2021
Carousel     1/4/2023
Photo        12/7/2021
...                                ...                    ...
             12/24/2014
             12/24/2014
             12/23/2014
             12/23/2014
             12/22/2014

                        Post Video Play Clicks Other Engagements Answers  \
Content Type Date
Carousel     1/30/2023
Photo        4/15/2022
Video        5/28/2021
Carousel     1/4/2023
Photo        12/7/2021
...                                        ...               ...     ...
             12/24/2014
             12/24/2014
             12/23/2014
             12/23/2014
             12/22/2014

                        App Engagements App Install Attempts App Opens  \
Content Type Date
Carousel     1/30/2023
Photo        4/15/2022
Video        5/28/2021
Carousel     1/4/2023
Photo        12/7/2021
...                                 ...                  ...       ...
             12/24/2014
             12/24/2014
             12/23/2014
             12/23/2014
             12/22/2014

                        Follows from Post Unfollows from Post  \
Content Type Date
Carousel     1/30/2023
Photo        4/15/2022
Video        5/28/2021
Carousel     1/4/2023
Photo        12/7/2021
...                                   ...                 ...
             12/24/2014
             12/24/2014
             12/23/2014
             12/23/2014
             12/22/2014

                        Negative Feedback bit.ly Link Clicks Engaged Users  \
Content Type Date
Carousel     1/30/2023
Photo        4/15/2022
Video        5/28/2021
Carousel     1/4/2023
Photo        12/7/2021
...                                   ...                ...           ...
             12/24/2014
             12/24/2014
             12/23/2014
             12/23/2014
             12/22/2014

                        Engaged Fans Users Talking About This  \
Content Type Date
Carousel     1/30/2023
Photo        4/15/2022
Video        5/28/2021
Carousel     1/4/2023
Photo        12/7/2021
...                              ...                      ...
             12/24/2014
             12/24/2014
             12/23/2014
             12/23/2014
             12/22/2014

                        Unique Reactions Unique Comments Unique Shares  \
Content Type Date
Carousel     1/30/2023
Photo        4/15/2022
Video        5/28/2021
Carousel     1/4/2023
Photo        12/7/2021
...                                  ...             ...           ...
             12/24/2014
             12/24/2014
             12/23/2014
             12/23/2014
             12/22/2014

                        Unique Answers Unique Post Clicks  \
Content Type Date
Carousel     1/30/2023
Photo        4/15/2022
Video        5/28/2021
Carousel     1/4/2023
Photo        12/7/2021
...                                ...                ...
             12/24/2014
             12/24/2014
             12/23/2014
             12/23/2014
             12/22/2014

                        Unique Post Link Clicks Unique Post Photo View Clicks  \
Content Type Date
Carousel     1/30/2023
Photo        4/15/2022
Video        5/28/2021
Carousel     1/4/2023
Photo        12/7/2021
...                                         ...                           ...
             12/24/2014
             12/24/2014
             12/23/2014
             12/23/2014
             12/22/2014

                        Unique Post Video Play Clicks  \
Content Type Date
Carousel     1/30/2023
Photo        4/15/2022
Video        5/28/2021
Carousel     1/4/2023
Photo        12/7/2021
...                                               ...
             12/24/2014
             12/24/2014
             12/23/2014
             12/23/2014
             12/22/2014

                        Unique Other Post Clicks Unique Negative Feedback  \
Content Type Date
Carousel     1/30/2023
Photo        4/15/2022
Video        5/28/2021
Carousel     1/4/2023
Photo        12/7/2021
...                                          ...                      ...
             12/24/2014
             12/24/2014
             12/23/2014
             12/23/2014
             12/22/2014

                        Subscribers Gained from Video Annotation Clicks  \
Content Type Date
Carousel     1/30/2023
Photo        4/15/2022
Video        5/28/2021
Carousel     1/4/2023
Photo        12/7/2021
...                                               ...               ...
             12/24/2014
             12/24/2014
             12/23/2014
             12/23/2014
             12/22/2014

                        Card Clicks Video Views Media Views  \
Content Type Date
Carousel     1/30/2023                        0
Photo        4/15/2022
Video        5/28/2021                   10,392
Carousel     1/4/2023                         0
Photo        12/7/2021
...                             ...         ...         ...
             12/24/2014
             12/24/2014
             12/23/2014
             12/23/2014
             12/22/2014

                        Organic Video Views Paid Video Views  \
Content Type Date
Carousel     1/30/2023                    0
Photo        4/15/2022
Video        5/28/2021               10,392
Carousel     1/4/2023                     0
Photo        12/7/2021
...                                     ...              ...
             12/24/2014
             12/24/2014
             12/23/2014
             12/23/2014
             12/22/2014

                        Partial Video Views Organic Partial Video Views  \
Content Type Date
Carousel     1/30/2023
Photo        4/15/2022
Video        5/28/2021
Carousel     1/4/2023
Photo        12/7/2021
...                                     ...                         ...
             12/24/2014
             12/24/2014
             12/23/2014
             12/23/2014
             12/22/2014

                        Paid Partial Video Views Full Video Views  \
Content Type Date
Carousel     1/30/2023
Photo        4/15/2022
Video        5/28/2021
Carousel     1/4/2023
Photo        12/7/2021
...                                          ...              ...
             12/24/2014
             12/24/2014
             12/23/2014
             12/23/2014
             12/22/2014

                        Full Video View Rate Follow Video Views  \
Content Type Date
Carousel     1/30/2023
Photo        4/15/2022
Video        5/28/2021
Carousel     1/4/2023
Photo        12/7/2021
...                                      ...                ...
             12/24/2014
             12/24/2014
             12/23/2014
             12/23/2014
             12/22/2014

                        For You Video Views Hashtag Video Views  \
Content Type Date
Carousel     1/30/2023
Photo        4/15/2022
Video        5/28/2021
Carousel     1/4/2023
Photo        12/7/2021
...                                     ...                 ...
             12/24/2014
             12/24/2014
             12/23/2014
             12/23/2014
             12/22/2014

                        Business Account Video Views Sound Video Views  \
Content Type Date
Carousel     1/30/2023
Photo        4/15/2022
Video        5/28/2021
Carousel     1/4/2023
Photo        12/7/2021
...                                              ...               ...
             12/24/2014
             12/24/2014
             12/23/2014
             12/23/2014
             12/22/2014

                        Unspecified Video Views Organic Full Video Views  \
Content Type Date
Carousel     1/30/2023
Photo        4/15/2022
Video        5/28/2021
Carousel     1/4/2023
Photo        12/7/2021
...                                         ...                      ...
             12/24/2014
             12/24/2014
             12/23/2014
             12/23/2014
             12/22/2014

                        Paid Full Video Views Autoplay Video Views  \
Content Type Date
Carousel     1/30/2023
Photo        4/15/2022
Video        5/28/2021
Carousel     1/4/2023
Photo        12/7/2021
...                                       ...                  ...
             12/24/2014
             12/24/2014
             12/23/2014
             12/23/2014
             12/22/2014

                        Click to Play Video Views Sound on Video Views  \
Content Type Date
Carousel     1/30/2023
Photo        4/15/2022
Video        5/28/2021
Carousel     1/4/2023
Photo        12/7/2021
...                                           ...                  ...
             12/24/2014
             12/24/2014
             12/23/2014
             12/23/2014
             12/22/2014

                        Sound off Video Views 10-Second Video Views  \
Content Type Date
Carousel     1/30/2023
Photo        4/15/2022
Video        5/28/2021
Carousel     1/4/2023
Photo        12/7/2021
...                                       ...                   ...
             12/24/2014
             12/24/2014
             12/23/2014
             12/23/2014
             12/22/2014

                        Organic 10-Second Video Views  \
Content Type Date

In [45]:
ig1.drop_index_col

AttributeError: 'DataFrame' object has no attribute 'drop_index_col'

In [10]:
for x in ig1:
    if ig1[x,'Impressions'] =='':
        drop(x, inplace == True)

KeyError: ('Date', 'Impressions')

In [171]:
ig.set_index(1)

AttributeError: 'Series' object has no attribute 'set_index'

In [114]:
ig1['Linked Content']= ig1['Linked Content'].apply(lambda x: str(x))
ig1['Linked Content'].str.replace('nan','')

Content Type
Carousel
Photo
Video
Carousel
Photo
           ..
Photo
Photo
Photo
Photo
Photo
Name: Linked Content, Length: 10000, dtype: object

In [28]:
ig1['Profile']

Content Type
Carousel    stanbicibtc
Photo       stanbicibtc
Video       stanbicibtc
Carousel    stanbicibtc
Photo       stanbicibtc
               ...
Photo       stanbicibtc
Photo       stanbicibtc
Photo       stanbicibtc
Photo       stanbicibtc
Photo       stanbicibtc
Name: Profile, Length: 10000, dtype: object

In [23]:
ig1.columns

Index(['Date', 'Post ID', 'Network', 'Post Type', 'Profile', 'Sent by', 'Link',
       'Post', 'Linked Content', 'Impressions',
       ...
       'Video Removed from Playlists', 'Annotation Impressions',
       'Annotation Clickable Impressions', 'Annotation Closable Impressions',
       'Annotation Closes', 'Card Impressions', 'Card Teaser Impressions',
       'Card Teaser Clicks', 'Poll Votes', 'Tags'],
      dtype='object', length=146)

## Personal Project

In [1]:
import pandas as pd

In [2]:
df = pd.read_excel(r'C:\Users\PRAISE\Downloads\xlsx files\Nashville Housing Data for Data Cleaning.xlsx')

In [3]:
df

,UniqueID,ParcelID,LandUse,PropertyAddress,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerAddress,Acreage,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath
0,2045,007 00 0 125.00,SINGLE FAMILY,"1808 FOX CHASE DR, GOODLETTSVILLE",2013-04-09,240000,20130412-0036474,No,"FRAZIER, CYRENTHA LYNETTE","1808 FOX CHASE DR, GOODLETTSVILLE, TN",2.3,GENERAL SERVICES DISTRICT,50000.0,168200.0,235700.0,1986.0,3.0,3.0,0.0
1,16918,007 00 0 130.00,SINGLE FAMILY,"1832 FOX CHASE DR, GOODLETTSVILLE",2014-06-10,366000,20140619-0053768,No,"BONER, CHARLES & LESLIE","1832 FOX CHASE DR, GOODLETTSVILLE, TN",3.5,GENERAL SERVICES DISTRICT,50000.0,264100.0,319000.0,1998.0,3.0,3.0,2.0
2,54582,007 00 0 138.00,SINGLE FAMILY,"1864 FOX CHASE DR, GOODLETTSVILLE",2016-09-26,435000,20160927-0101718,No,"WILSON, JAMES E. & JOANNE","1864 FOX CHASE DR, GOODLETTSVILLE, TN",2.9,GENERAL SERVICES DISTRICT,50000.0,216200.0,298000.0,1987.0,4.0,3.0,0.0
3,43070,007 00 0 143.00,SINGLE FAMILY,"1853 FOX CHASE DR, GOODLETTSVILLE",2016-01-29,255000,20160129-0008913,No,"BAKER, JAY K. & SUSAN E.","1853 FOX CHASE DR, GOODLETTSVILLE, TN",2.6,GENERAL SERVICES DISTRICT,50000.0,147300.0,197300.0,1985.0,3.0,3.0,0.0
4,22714,007 00 0 149.00,SINGLE FAMILY,"1829 FOX CHASE DR, GOODLETTSVILLE",2014-10-10,278000,20141015-0095255,No,"POST, CHRISTOPHER M. & SAMANTHA C.","1829 FOX CHASE DR, GOODLETTSVILLE, TN",2.0,GENERAL SERVICES DISTRICT,50000.0,152300.0,202300.0,1984.0,4.0,3.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56472,30469,188 10 0A 101.00,SINGLE FAMILY,"1435 WINDING CREEK DR, NOLENSVILLE",2015-05-27,157500,20150608-0053286,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56473,27707,188 10 0A 107.00,SINGLE FAMILY,"1423 WINDING CREEK DR, NOLENSVILLE",2015-03-02,145000,20150304-0019013,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56474,52709,188 10 0A 118.00,VACANT RESIDENTIAL LAND,"1804 GRACE POINT LN, NOLENSVILLE",2016-08-16,234611,20160819-0087214,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56475,54042,188 10 0A 121.00,VACANT RESIDENTIAL LAND,"1709 PARK TERRACE LN, NOLENSVILLE",2016-09-07,93844,20160919-0098411,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56476,54043,188 10 0A 122.00,VACANT RESIDENTIAL LAND,"1713 PARK TERRACE LN, NOLENSVILLE",2016-09-07,93844,20160919-0098411,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
df.LandUse.first_valid_index()

0

In [19]:
df.first_valid_index()

0

In [30]:
df.LandUse.count()

56477

In [35]:
df.LandUse

0                  SINGLE FAMILY
1                  SINGLE FAMILY
2                  SINGLE FAMILY
3                  SINGLE FAMILY
4                  SINGLE FAMILY
                  ...
56472              SINGLE FAMILY
56473              SINGLE FAMILY
56474    VACANT RESIDENTIAL LAND
56475    VACANT RESIDENTIAL LAND
56476    VACANT RESIDENTIAL LAND
Name: LandUse, Length: 56477, dtype: object

In [41]:
df['SaleDate'].unique

<bound method Series.unique of 0       2013-04-09
1       2014-06-10
2       2016-09-26
3       2016-01-29
4       2014-10-10
           ...
56472   2015-05-27
56473   2015-03-02
56474   2016-08-16
56475   2016-09-07
56476   2016-09-07
Name: SaleDate, Length: 56477, dtype: datetime64[ns]>

In [4]:
df.notnull().count()

UniqueID           56477
ParcelID           56477
LandUse            56477
PropertyAddress    56477
SaleDate           56477
SalePrice          56477
LegalReference     56477
SoldAsVacant       56477
OwnerName          56477
OwnerAddress       56477
Acreage            56477
TaxDistrict        56477
LandValue          56477
BuildingValue      56477
TotalValue         56477
YearBuilt          56477
Bedrooms           56477
FullBath           56477
HalfBath           56477
dtype: int64

In [8]:
df = df.drop_duplicates()

In [9]:
df.count()

UniqueID           56477
ParcelID           56477
LandUse            56477
PropertyAddress    56448
SaleDate           56477
SalePrice          56477
LegalReference     56477
SoldAsVacant       56477
OwnerName          25261
OwnerAddress       26015
Acreage            26015
TaxDistrict        26015
LandValue          26015
BuildingValue      26015
TotalValue         26015
YearBuilt          24163
Bedrooms           24157
FullBath           24275
HalfBath           24144
dtype: int64

In [11]:
df.describe()

,UniqueID,SalePrice,Acreage,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath
count,56477.000000,5.647700e+04,26015.000000,2.601500e+04,2.601500e+04,2.601500e+04,24163.000000,24157.000000,24275.000000,24144.000000
mean,28334.001133,3.272264e+05,0.498923,6.906856e+04,1.607847e+05,2.323754e+05,1963.744899,3.089912,1.886014,0.283921
std,16352.590651,9.298326e+05,1.570454,1.060401e+05,2.067999e+05,2.810643e+05,26.542982,0.852869,0.961515,0.487881
min,0.000000,5.000000e+01,0.010000,1.000000e+02,0.000000e+00,1.000000e+02,1799.000000,0.000000,0.000000,0.000000
25%,14186.000000,1.350000e+05,0.180000,2.100000e+04,7.590000e+04,1.028000e+05,1948.000000,3.000000,1.000000,0.000000
50%,28313.000000,2.051000e+05,0.270000,2.880000e+04,1.114000e+05,1.485000e+05,1960.000000,3.000000,2.000000,0.000000
75%,42513.000000,3.285000e+05,0.450000,6.000000e+04,1.807000e+05,2.683500e+05,1983.000000,3.000000,2.000000,1.000000
max,56635.000000,5.427806e+07,160.060000,2.772000e+06,1.297180e+07,1.394040e+07,2017.000000,11.000000,10.000000,3.000000

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 56477 entries, 0 to 56476
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   UniqueID         56477 non-null  int64
 1   ParcelID         56477 non-null  object
 2   LandUse          56477 non-null  object
 3   PropertyAddress  56448 non-null  object
 4   SaleDate         56477 non-null  datetime64[ns]
 5   SalePrice        56477 non-null  int64
 6   LegalReference   56477 non-null  object
 7   SoldAsVacant     56477 non-null  object
 8   OwnerName        25261 non-null  object
 9   OwnerAddress     26015 non-null  object
 10  Acreage          26015 non-null  float64
 11  TaxDistrict      26015 non-null  object
 12  LandValue        26015 non-null  float64
 13  BuildingValue    26015 non-null  float64
 14  TotalValue       26015 non-null  float64
 15  YearBuilt        24163 non-null  float64
 16  Bedrooms         24157 non-null  float64
 17  FullBath         24275 non-null  float64
 18  HalfBath         24144 non-null  float64
dtypes: datetime64[ns](1), float64(8), int64(2), object(8)
memory usage: 8.6+ MB

In [145]:
df.columns

Index(['UniqueID ', 'ParcelID', 'LandUse', 'PropertyAddress', 'SaleDate',
       'SalePrice', 'LegalReference', 'SoldAsVacant', 'OwnerName',
       'OwnerAddress', 'Acreage', 'TaxDistrict', 'LandValue', 'BuildingValue',
       'TotalValue', 'YearBuilt', 'Bedrooms', 'FullBath', 'HalfBath'],
      dtype='object')

In [15]:
pd.set_option('display.max.rows', 20)

df['LandUse'].unique()

array(['SINGLE FAMILY', 'RESIDENTIAL CONDO', 'VACANT RURAL LAND',
       'VACANT RES LAND', 'DUPLEX', 'VACANT RESIDENTIAL LAND', 'CHURCH',
       'ZERO LOT LINE', 'RESIDENTIAL COMBO/MISC', 'PARSONAGE',
       'OFFICE BLDG (ONE OR TWO STORIES)',
       'GREENBELT/RES_x000D_\nGRRENBELT/RES', 'MOBILE HOME',
       'PARKING LOT', 'CLUB/UNION HALL/LODGE', 'TRIPLEX',
       'VACANT ZONED MULTI FAMILY', 'SPLIT CLASS', 'CONDO', 'QUADPLEX',
       'LIGHT MANUFACTURING', 'FOREST', 'CONVENIENCE MARKET WITHOUT GAS',
       'DORMITORY/BOARDING HOUSE', 'GREENBELT', 'DAY CARE CENTER',
       'METRO OTHER THAN OFC, SCHOOL,HOSP, OR PARK',
       'TERMINAL/DISTRIBUTION WAREHOUSE', 'NIGHTCLUB/LOUNGE',
       'RESTURANT/CAFETERIA', 'VACANT COMMERCIAL LAND',
       'CONDOMINIUM OFC  OR OTHER COM CONDO', 'STRIP SHOPPING CENTER',
       'VACANT RESIENTIAL LAND', 'APARTMENT: LOW RISE (BUILT SINCE 1960)',
       'ONE STORY GENERAL RETAIL STORE', 'NON-PROFIT CHARITABLE SERVICE',
       'SMALL SERVICE SHOP', 'MORTUARY/CEMETERY'], dtype=object)

### Checking if the Landuse rows have similar data

In [17]:
vacant= ['VACANT RESIDENTIAL LAND','VACANT RES LAND']
df[df['LandUse'].isin(vacant)].sort_values(by = 'SaleDate', ascending = True)

#df[df['LandUse'].str.contains('VACANT RES LAND')]

,UniqueID,ParcelID,LandUse,PropertyAddress,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerAddress,Acreage,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath
15358,298,083 05 0 450.00,VACANT RES LAND,"800 N 14TH ST, NASHVILLE",2013-01-02,72500,20130107-0001758,No,"FREEDMAN, RYAN J.","800 N 14TH ST, NASHVILLE, TN",0.15,URBAN SERVICES DISTRICT,60000.0,368200.0,459800.0,2013.0,5.0,3.0,1.0
35653,153,128 12 0C 049.00,VACANT RES LAND,"1123 WOODBURY FALLS CT, NASHVILLE",2013-01-04,194000,20130108-0002501,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55886,82,182 12 0A 148.00,VACANT RES LAND,"7204 SMOKEY HILL RD, ANTIOCH",2013-01-04,50000,20130114-0004275,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55880,81,182 12 0A 145.00,VACANT RES LAND,"7405 GOLDEN APPLE DR, ANTIOCH",2013-01-04,50000,20130114-0004275,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30072,365,110 03 0A 054.00,VACANT RES LAND,"2736 ALVIN SPERRY PASS, MOUNT JULIET",2013-01-07,188076,20130109-0002805,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32134,55719,117 07 0 112.00,VACANT RESIDENTIAL LAND,"3426 HOPKINS ST, NASHVILLE",2016-10-31,434700,20161102-0115808,No,"SIDWELL, K. THOMAS","3426 HOPKINS ST, NASHVILLE, TN",0.46,URBAN SERVICES DISTRICT,220000.0,146600.0,366600.0,1958.0,3.0,1.0,1.0
11350,56353,075 11 0 060.00,VACANT RESIDENTIAL LAND,"668 MERCER DR, HERMITAGE",2016-10-31,1500,20161101-0115350,Yes,"BULLINGTON, GREG & K.","668 MERCER DR, HERMITAGE, TN",0.12,GENERAL SERVICES DISTRICT,2500.0,0.0,2500.0,NaN,NaN,NaN,NaN
39194,56477,135 00 0 295.00,VACANT RESIDENTIAL LAND,"0 UNA RECREATION RD, NASHVILLE",2016-10-31,89900,20161102-0115670,Yes,"CORDELL, DWIGHT, III","0 UNA RECREATION RD, NASHVILLE, TN",3.00,URBAN SERVICES DISTRICT,60000.0,0.0,60000.0,NaN,NaN,NaN,NaN
19855,55558,092 03 0 116.00,VACANT RESIDENTIAL LAND,"2401 ALAMEDA ST, NASHVILLE",2016-10-31,75000,20161102-0115785,No,"RHYTHM HOMES AND DEVELOPMENT, LLC","2401 ALAMEDA ST, NASHVILLE, TN",0.18,URBAN SERVICES DISTRICT,11000.0,0.0,11000.0,NaN,NaN,NaN,NaN
51255,55456,172 03 0A 125.00,VACANT RESIDENTIAL LAND,"1636 BOXWOOD DR, NASHVILLE",2016-10-31,398887,20161101-0115386,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
name=['FREEDMAN, RYAN J.']

In [62]:
df[df['OwnerName'].isin(name)]

,UniqueID,ParcelID,LandUse,PropertyAddress,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerAddress,Acreage,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath
15358,298,083 05 0 450.00,VACANT RES LAND,"800 N 14TH ST, NASHVILLE",2013-01-02,72500,20130107-0001758,No,"FREEDMAN, RYAN J.","800 N 14TH ST, NASHVILLE, TN",0.15,URBAN SERVICES DISTRICT,60000.0,368200.0,459800.0,2013.0,5.0,3.0,1.0
15359,8101,083 05 0 450.00,SINGLE FAMILY,"800 N 14TH ST, NASHVILLE",2013-09-03,507235,20130904-0093001,No,"FREEDMAN, RYAN J.","800 N 14TH ST, NASHVILLE, TN",0.15,URBAN SERVICES DISTRICT,60000.0,368200.0,459800.0,2013.0,5.0,3.0,1.0

### it is possible this guy sold the same property twice

In [58]:
aa = df[df['LandUse'].str.contains('VACANT RESIDENTIAL LAND')]
aa.count()

UniqueID           3547
ParcelID           3547
LandUse            3547
PropertyAddress    3542
SaleDate           3547
SalePrice          3547
LegalReference     3547
SoldAsVacant       3547
OwnerName          1103
OwnerAddress       1245
Acreage            1245
TaxDistrict        1245
LandValue          1245
BuildingValue      1245
TotalValue         1245
YearBuilt           270
Bedrooms            274
FullBath            366
HalfBath            348
dtype: int64

In [59]:
aa = df[df['LandUse'].str.contains('VACANT RESIENTIAL LAND')]
aa.count()

UniqueID           3
ParcelID           3
LandUse            3
PropertyAddress    3
SaleDate           3
SalePrice          3
LegalReference     3
SoldAsVacant       3
OwnerName          3
OwnerAddress       3
Acreage            3
TaxDistrict        3
LandValue          3
BuildingValue      3
TotalValue         3
YearBuilt          0
Bedrooms           0
FullBath           0
HalfBath           0
dtype: int64

In [49]:
df.count()

UniqueID           56477
ParcelID           56477
LandUse            56477
PropertyAddress    56448
SaleDate           56477
SalePrice          56477
LegalReference     56477
SoldAsVacant       56477
OwnerName          25261
OwnerAddress       26015
Acreage            26015
TaxDistrict        26015
LandValue          26015
BuildingValue      26015
TotalValue         26015
YearBuilt          24163
Bedrooms           24157
FullBath           24275
HalfBath           24144
dtype: int64

In [70]:
df['LandUse'] = df['LandUse'].replace('VACANT RES LAND','VACANT RESIDENTIAL LAND')

In [71]:
df[df['LandUse'].str.contains('VACANT RESIENTIAL LAND')]

,UniqueID,ParcelID,LandUse,PropertyAddress,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerAddress,Acreage,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath
17696,31640,087 02 0 083.00,VACANT RESIENTIAL LAND,"0 RACCOON TRL, HERMITAGE",2015-05-22,220000,20150529-0049626,No,"PROGRESS RESIDENTIAL 2015-3 BORROWER, LLC","0 RACCOON TRL, HERMITAGE, TN",0.46,GENERAL SERVICES DISTRICT,35000.0,0.0,35000.0,NaN,NaN,NaN,NaN
46712,30909,158 00 0 119.00,VACANT RESIENTIAL LAND,"1627 OLD HICKORY BLVD, BRENTWOOD",2015-05-22,230000,20150602-0051451,Yes,"WILSON, JARED J. & KENDAL BRINKLEY","1627 OLD HICKORY BLVD, BRENTWOOD, TN",1.15,GENERAL SERVICES DISTRICT,240000.0,0.0,240000.0,NaN,NaN,NaN,NaN
46713,40470,158 00 0 119.00,VACANT RESIENTIAL LAND,"1627 OLD HICKORY BLVD, BRENTWOOD",2015-11-20,607642,20151201-0121075,No,"WILSON, JARED J. & KENDAL BRINKLEY","1627 OLD HICKORY BLVD, BRENTWOOD, TN",1.15,GENERAL SERVICES DISTRICT,240000.0,0.0,240000.0,NaN,NaN,NaN,NaN

In [64]:
vacant= ['VACANT RESIENTIAL LAND']

In [65]:
df[df['LandUse'].isin(vacant)]

,UniqueID,ParcelID,LandUse,PropertyAddress,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerAddress,Acreage,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath
17696,31640,087 02 0 083.00,VACANT RESIENTIAL LAND,"0 RACCOON TRL, HERMITAGE",2015-05-22,220000,20150529-0049626,No,"PROGRESS RESIDENTIAL 2015-3 BORROWER, LLC","0 RACCOON TRL, HERMITAGE, TN",0.46,GENERAL SERVICES DISTRICT,35000.0,0.0,35000.0,NaN,NaN,NaN,NaN
46712,30909,158 00 0 119.00,VACANT RESIENTIAL LAND,"1627 OLD HICKORY BLVD, BRENTWOOD",2015-05-22,230000,20150602-0051451,Yes,"WILSON, JARED J. & KENDAL BRINKLEY","1627 OLD HICKORY BLVD, BRENTWOOD, TN",1.15,GENERAL SERVICES DISTRICT,240000.0,0.0,240000.0,NaN,NaN,NaN,NaN
46713,40470,158 00 0 119.00,VACANT RESIENTIAL LAND,"1627 OLD HICKORY BLVD, BRENTWOOD",2015-11-20,607642,20151201-0121075,No,"WILSON, JARED J. & KENDAL BRINKLEY","1627 OLD HICKORY BLVD, BRENTWOOD, TN",1.15,GENERAL SERVICES DISTRICT,240000.0,0.0,240000.0,NaN,NaN,NaN,NaN

In [5]:
df['LandUse'] = df['LandUse'].str.replace('GREENBELT/RES_x000D_\nGRRENBELT/RES', 'GREENBELT')

In [84]:
df['LandUse'] = df['LandUse'].str.replace('VACANT RESIENTIAL LAND','VACANT RESIDENTIAL LAND')

In [87]:
df['LandUse'].unique()

array(['SINGLE FAMILY', 'RESIDENTIAL CONDO', 'VACANT RURAL LAND',
       'VACANT RESIDENTIAL LAND', 'DUPLEX', 'CHURCH', 'ZERO LOT LINE',
       'RESIDENTIAL COMBO/MISC', 'PARSONAGE',
       'OFFICE BLDG (ONE OR TWO STORIES)', 'GREENBELT', 'MOBILE HOME',
       'PARKING LOT', 'CLUB/UNION HALL/LODGE', 'TRIPLEX',
       'VACANT ZONED MULTI FAMILY', 'SPLIT CLASS', 'CONDO', 'QUADPLEX',
       'LIGHT MANUFACTURING', 'FOREST', 'CONVENIENCE MARKET WITHOUT GAS',
       'DORMITORY/BOARDING HOUSE', 'DAY CARE CENTER',
       'METRO OTHER THAN OFC, SCHOOL,HOSP, OR PARK',
       'TERMINAL/DISTRIBUTION WAREHOUSE', 'NIGHTCLUB/LOUNGE',
       'RESTURANT/CAFETERIA', 'VACANT COMMERCIAL LAND',
       'CONDOMINIUM OFFICE', 'STRIP SHOPPING CENTER',
       'APARTMENT: LOW RISE (BUILT SINCE 1960)',
       'ONE STORY GENERAL RETAIL STORE', 'NON-PROFIT CHARITABLE SERVICE',
       'SMALL SERVICE SHOP', 'MORTUARY/CEMETERY'], dtype=object)

In [86]:
df['LandUse'] = df['LandUse'].str.replace('CONDOMINIUM OFC  OR OTHER COM CONDO','CONDOMINIUM OFFICE')

In [ ]:
df['LandUse'] = df['LandUse'].str.replace('CONDOMINIUM OFC  OR OTHER COM CONDO','CONDOMINIUM OFFICE')

In [95]:
df[df['LandUse'].str.contains('STRIP SHOPPING CENTER')]
df['LandUse'] = df['LandUse'].str.replace('STRIP SHOPPING CENTER','SHOPPING CENTER')

In [102]:
df['LandUse']= df['LandUse'].str.replace('OFFICE BLDG (ONE OR TWO STORIES)','OFFICE BUILDING')

C:\Users\PRAISE\AppData\Local\Temp\ipykernel_10120\942015516.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df['LandUse']= df['LandUse'].str.replace('OFFICE BLDG (ONE OR TWO STORIES)','OFFICE BUILDING')

In [103]:
df['LandUse'].unique()

array(['SINGLE FAMILY', 'RESIDENTIAL CONDO', 'VACANT RURAL LAND',
       'VACANT RESIDENTIAL LAND', 'DUPLEX', 'CHURCH', 'ZERO LOT LINE',
       'RESIDENTIAL COMBO/MISC', 'PARSONAGE',
       'OFFICE BLDG (ONE OR TWO STORIES)', 'GREENBELT', 'MOBILE HOME',
       'PARKING LOT', 'CLUB/UNION HALL/LODGE', 'TRIPLEX',
       'VACANT ZONED MULTI FAMILY', 'SPLIT CLASS', 'CONDO', 'QUADPLEX',
       'LIGHT MANUFACTURING', 'FOREST', 'CONVENIENCE MARKET WITHOUT GAS',
       'DORMITORY/BOARDING HOUSE', 'DAY CARE CENTER',
       'METRO OTHER THAN OFC, SCHOOL,HOSP, OR PARK',
       'TERMINAL/DISTRIBUTION WAREHOUSE', 'NIGHTCLUB/LOUNGE',
       'RESTURANT/CAFETERIA', 'VACANT COMMERCIAL LAND',
       'CONDOMINIUM OFFICE', 'SHOPPING CENTER',
       'APARTMENT: LOW RISE (BUILT SINCE 1960)',
       'ONE STORY GENERAL RETAIL STORE', 'NON-PROFIT CHARITABLE SERVICE',
       'SMALL SERVICE SHOP', 'MORTUARY/CEMETERY'], dtype=object)

In [104]:
df[df['LandUse'].str.contains('ONE STORY GENERAL RETAIL STORE')]

,UniqueID,ParcelID,LandUse,PropertyAddress,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerAddress,Acreage,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath
20640,25292,093 04 0 050.00,ONE STORY GENERAL RETAIL STORE,"608 SHELBY AVE, NASHVILLE",2014-12-15,258000,20141215-0114517,No,"NASHVILLE REAL ESTATE INVESTMENTS, LLC","608 SHELBY AVE, NASHVILLE, TN",0.3,URBAN SERVICES DISTRICT,63000.0,134500.0,203200.0,1925.0,0.0,0.0,0.0

In [65]:
df['LandUse'] = df['LandUse'].str.replace('OFFICE BLDG (ONE OR TWO STORIES)','OFFICE BUILDING')
#df[df['LandUse'].str.contains('ONE OR TWO STORIES')]

C:\Users\PRAISE\AppData\Local\Temp\ipykernel_10120\1416024403.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df['LandUse'] = df['LandUse'].str.replace('OFFICE BLDG (ONE OR TWO STORIES)','OFFICE BUILDING')

In [57]:
df[df['LandUse'].str.contains('OFFICE BUILDING

Empty DataFrame
Columns: [UniqueID , ParcelID, LandUse, PropertyAddress, SaleDate, SalePrice, LegalReference, SoldAsVacant, OwnerName, OwnerAddress, Acreage, TaxDistrict, LandValue, BuildingValue, TotalValue, YearBuilt, Bedrooms, FullBath, HalfBath]
Index: []

In [9]:
df[df.duplicated()]
df

,UniqueID,ParcelID,LandUse,PropertyAddress,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerAddress,Acreage,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath
0,2045,007 00 0 125.00,SINGLE FAMILY,"1808 FOX CHASE DR, GOODLETTSVILLE",2013-04-09,240000,20130412-0036474,No,"FRAZIER, CYRENTHA LYNETTE","1808 FOX CHASE DR, GOODLETTSVILLE, TN",2.3,GENERAL SERVICES DISTRICT,50000.0,168200.0,235700.0,1986.0,3.0,3.0,0.0
1,16918,007 00 0 130.00,SINGLE FAMILY,"1832 FOX CHASE DR, GOODLETTSVILLE",2014-06-10,366000,20140619-0053768,No,"BONER, CHARLES & LESLIE","1832 FOX CHASE DR, GOODLETTSVILLE, TN",3.5,GENERAL SERVICES DISTRICT,50000.0,264100.0,319000.0,1998.0,3.0,3.0,2.0
2,54582,007 00 0 138.00,SINGLE FAMILY,"1864 FOX CHASE DR, GOODLETTSVILLE",2016-09-26,435000,20160927-0101718,No,"WILSON, JAMES E. & JOANNE","1864 FOX CHASE DR, GOODLETTSVILLE, TN",2.9,GENERAL SERVICES DISTRICT,50000.0,216200.0,298000.0,1987.0,4.0,3.0,0.0
3,43070,007 00 0 143.00,SINGLE FAMILY,"1853 FOX CHASE DR, GOODLETTSVILLE",2016-01-29,255000,20160129-0008913,No,"BAKER, JAY K. & SUSAN E.","1853 FOX CHASE DR, GOODLETTSVILLE, TN",2.6,GENERAL SERVICES DISTRICT,50000.0,147300.0,197300.0,1985.0,3.0,3.0,0.0
4,22714,007 00 0 149.00,SINGLE FAMILY,"1829 FOX CHASE DR, GOODLETTSVILLE",2014-10-10,278000,20141015-0095255,No,"POST, CHRISTOPHER M. & SAMANTHA C.","1829 FOX CHASE DR, GOODLETTSVILLE, TN",2.0,GENERAL SERVICES DISTRICT,50000.0,152300.0,202300.0,1984.0,4.0,3.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56472,30469,188 10 0A 101.00,SINGLE FAMILY,"1435 WINDING CREEK DR, NOLENSVILLE",2015-05-27,157500,20150608-0053286,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56473,27707,188 10 0A 107.00,SINGLE FAMILY,"1423 WINDING CREEK DR, NOLENSVILLE",2015-03-02,145000,20150304-0019013,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56474,52709,188 10 0A 118.00,VACANT RESIDENTIAL LAND,"1804 GRACE POINT LN, NOLENSVILLE",2016-08-16,234611,20160819-0087214,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56475,54042,188 10 0A 121.00,VACANT RESIDENTIAL LAND,"1709 PARK TERRACE LN, NOLENSVILLE",2016-09-07,93844,20160919-0098411,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56476,54043,188 10 0A 122.00,VACANT RESIDENTIAL LAND,"1713 PARK TERRACE LN, NOLENSVILLE",2016-09-07,93844,20160919-0098411,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:

#df['PropertyAddress'].mask(df['OwnerAddress']).isna(),df['PropertyAddress']

#df['OwnerAddress'] = df['OwnerAddress'].fillna('')
#for x in df.index:
#    if df.loc[x,'PropertyAddress'] != df['OwnerAddress']:
#        df['PropertyAddress'] = df.replace(x,df['OwnerAddress'])
        
#df
#df [‘PropertyAddress’] = df [‘PropertyAddress’].where (df [‘PropertyAddress’] == df [‘OwnerAddress’], df [‘OwnerAddress’])
#df = pd.read_excel(r'C:\Users\PRAISE\Downloads\xlsx files\Nashville Housing Data for Data Cleaning.xlsx')
df['OwnerAddress'].where (df ['PropertyAddress'] == df ['OwnerAddress'], df ['PropertyAddress'])

0         1808  FOX CHASE DR, GOODLETTSVILLE
1         1832  FOX CHASE DR, GOODLETTSVILLE
2         1864 FOX CHASE  DR, GOODLETTSVILLE
3         1853  FOX CHASE DR, GOODLETTSVILLE
4         1829  FOX CHASE DR, GOODLETTSVILLE
                        ...
56472    1435  WINDING CREEK DR, NOLENSVILLE
56473    1423  WINDING CREEK DR, NOLENSVILLE
56474      1804 GRACE POINT  LN, NOLENSVILLE
56475     1709 PARK TERRACE  LN, NOLENSVILLE
56476     1713 PARK TERRACE  LN, NOLENSVILLE
Name: OwnerAddress, Length: 56477, dtype: object

In [17]:
df

,UniqueID,ParcelID,LandUse,PropertyAddress,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerAddress,Acreage,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath
0,2045,007 00 0 125.00,SINGLE FAMILY,"1808 FOX CHASE DR, GOODLETTSVILLE, TN",2013-04-09,240000,20130412-0036474,No,"FRAZIER, CYRENTHA LYNETTE","1808 FOX CHASE DR, GOODLETTSVILLE, TN",2.3,GENERAL SERVICES DISTRICT,50000.0,168200.0,235700.0,1986.0,3.0,3.0,0.0
1,16918,007 00 0 130.00,SINGLE FAMILY,"1832 FOX CHASE DR, GOODLETTSVILLE, TN",2014-06-10,366000,20140619-0053768,No,"BONER, CHARLES & LESLIE","1832 FOX CHASE DR, GOODLETTSVILLE, TN",3.5,GENERAL SERVICES DISTRICT,50000.0,264100.0,319000.0,1998.0,3.0,3.0,2.0
2,54582,007 00 0 138.00,SINGLE FAMILY,"1864 FOX CHASE DR, GOODLETTSVILLE, TN",2016-09-26,435000,20160927-0101718,No,"WILSON, JAMES E. & JOANNE","1864 FOX CHASE DR, GOODLETTSVILLE, TN",2.9,GENERAL SERVICES DISTRICT,50000.0,216200.0,298000.0,1987.0,4.0,3.0,0.0
3,43070,007 00 0 143.00,SINGLE FAMILY,"1853 FOX CHASE DR, GOODLETTSVILLE, TN",2016-01-29,255000,20160129-0008913,No,"BAKER, JAY K. & SUSAN E.","1853 FOX CHASE DR, GOODLETTSVILLE, TN",2.6,GENERAL SERVICES DISTRICT,50000.0,147300.0,197300.0,1985.0,3.0,3.0,0.0
4,22714,007 00 0 149.00,SINGLE FAMILY,"1829 FOX CHASE DR, GOODLETTSVILLE, TN",2014-10-10,278000,20141015-0095255,No,"POST, CHRISTOPHER M. & SAMANTHA C.","1829 FOX CHASE DR, GOODLETTSVILLE, TN",2.0,GENERAL SERVICES DISTRICT,50000.0,152300.0,202300.0,1984.0,4.0,3.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56472,30469,188 10 0A 101.00,SINGLE FAMILY,NaN,2015-05-27,157500,20150608-0053286,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56473,27707,188 10 0A 107.00,SINGLE FAMILY,NaN,2015-03-02,145000,20150304-0019013,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56474,52709,188 10 0A 118.00,VACANT RESIDENTIAL LAND,NaN,2016-08-16,234611,20160819-0087214,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56475,54042,188 10 0A 121.00,VACANT RESIDENTIAL LAND,NaN,2016-09-07,93844,20160919-0098411,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56476,54043,188 10 0A 122.00,VACANT RESIDENTIAL LAND,NaN,2016-09-07,93844,20160919-0098411,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
df

,UniqueID,ParcelID,LandUse,PropertyAddress,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerAddress,Acreage,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath
0,2045,007 00 0 125.00,SINGLE FAMILY,"1808 FOX CHASE DR, GOODLETTSVILLE",2013-04-09,240000,20130412-0036474,No,"FRAZIER, CYRENTHA LYNETTE","1808 FOX CHASE DR, GOODLETTSVILLE, TN",2.3,GENERAL SERVICES DISTRICT,50000.0,168200.0,235700.0,1986.0,3.0,3.0,0.0
1,16918,007 00 0 130.00,SINGLE FAMILY,"1832 FOX CHASE DR, GOODLETTSVILLE",2014-06-10,366000,20140619-0053768,No,"BONER, CHARLES & LESLIE","1832 FOX CHASE DR, GOODLETTSVILLE, TN",3.5,GENERAL SERVICES DISTRICT,50000.0,264100.0,319000.0,1998.0,3.0,3.0,2.0
2,54582,007 00 0 138.00,SINGLE FAMILY,"1864 FOX CHASE DR, GOODLETTSVILLE",2016-09-26,435000,20160927-0101718,No,"WILSON, JAMES E. & JOANNE","1864 FOX CHASE DR, GOODLETTSVILLE, TN",2.9,GENERAL SERVICES DISTRICT,50000.0,216200.0,298000.0,1987.0,4.0,3.0,0.0
3,43070,007 00 0 143.00,SINGLE FAMILY,"1853 FOX CHASE DR, GOODLETTSVILLE",2016-01-29,255000,20160129-0008913,No,"BAKER, JAY K. & SUSAN E.","1853 FOX CHASE DR, GOODLETTSVILLE, TN",2.6,GENERAL SERVICES DISTRICT,50000.0,147300.0,197300.0,1985.0,3.0,3.0,0.0
4,22714,007 00 0 149.00,SINGLE FAMILY,"1829 FOX CHASE DR, GOODLETTSVILLE",2014-10-10,278000,20141015-0095255,No,"POST, CHRISTOPHER M. & SAMANTHA C.","1829 FOX CHASE DR, GOODLETTSVILLE, TN",2.0,GENERAL SERVICES DISTRICT,50000.0,152300.0,202300.0,1984.0,4.0,3.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56472,30469,188 10 0A 101.00,SINGLE FAMILY,"1435 WINDING CREEK DR, NOLENSVILLE",2015-05-27,157500,20150608-0053286,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56473,27707,188 10 0A 107.00,SINGLE FAMILY,"1423 WINDING CREEK DR, NOLENSVILLE",2015-03-02,145000,20150304-0019013,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56474,52709,188 10 0A 118.00,VACANT RESIDENTIAL LAND,"1804 GRACE POINT LN, NOLENSVILLE",2016-08-16,234611,20160819-0087214,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56475,54042,188 10 0A 121.00,VACANT RESIDENTIAL LAND,"1709 PARK TERRACE LN, NOLENSVILLE",2016-09-07,93844,20160919-0098411,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56476,54043,188 10 0A 122.00,VACANT RESIDENTIAL LAND,"1713 PARK TERRACE LN, NOLENSVILLE",2016-09-07,93844,20160919-0098411,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df[df['LandUse'].isin(lists)]

,UniqueID,ParcelID,LandUse,PropertyAddress,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerAddress,Acreage,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath
1544,43128,042 11 0 030.00,OFFICE BLDG (ONE OR TWO STORIES),"632 OLD HICKORY BLVD, MADISON",2016-01-19,225000,20160121-0006356,No,"J.E.T. PRODUCTIONS, INC.","632 OLD HICKORY BLVD, MADISON, TN",0.87,GENERAL SERVICES DISTRICT,35000.0,163900.0,203500.0,1955.0,3.0,1.0,0.0
13981,14919,082 09 0 254.00,OFFICE BLDG (ONE OR TWO STORIES),"707 MONROE ST, NASHVILLE",2014-04-24,520000,20140502-0037596,No,"CROSSROADS CAMPUS, THE","707 MONROE ST, NASHVILLE, TN",0.18,URBAN SERVICES DISTRICT,40000.0,675400.0,715400.0,1910.0,0.0,3.0,0.0

In [16]:
df[df['LandUse'].str.extract('OFFICE BLDG (ONE OR TWO STORIES)')]

,UniqueID,ParcelID,LandUse,PropertyAddress,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerAddress,Acreage,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath
0,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56472,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56473,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56474,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56475,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56476,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
for x in df.index:
    if df.loc[x,'LandUse'] == 'OFFICE BLDG (ONE OR TWO STORIES)':
        df.drop(x, inplace = True)
        
df

,UniqueID,ParcelID,LandUse,PropertyAddress,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerAddress,Acreage,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath
0,2045,007 00 0 125.00,SINGLE FAMILY,"1808 FOX CHASE DR, GOODLETTSVILLE",2013-04-09,240000,20130412-0036474,No,"FRAZIER, CYRENTHA LYNETTE","1808 FOX CHASE DR, GOODLETTSVILLE, TN",2.3,GENERAL SERVICES DISTRICT,50000.0,168200.0,235700.0,1986.0,3.0,3.0,0.0
1,16918,007 00 0 130.00,SINGLE FAMILY,"1832 FOX CHASE DR, GOODLETTSVILLE",2014-06-10,366000,20140619-0053768,No,"BONER, CHARLES & LESLIE","1832 FOX CHASE DR, GOODLETTSVILLE, TN",3.5,GENERAL SERVICES DISTRICT,50000.0,264100.0,319000.0,1998.0,3.0,3.0,2.0
2,54582,007 00 0 138.00,SINGLE FAMILY,"1864 FOX CHASE DR, GOODLETTSVILLE",2016-09-26,435000,20160927-0101718,No,"WILSON, JAMES E. & JOANNE","1864 FOX CHASE DR, GOODLETTSVILLE, TN",2.9,GENERAL SERVICES DISTRICT,50000.0,216200.0,298000.0,1987.0,4.0,3.0,0.0
3,43070,007 00 0 143.00,SINGLE FAMILY,"1853 FOX CHASE DR, GOODLETTSVILLE",2016-01-29,255000,20160129-0008913,No,"BAKER, JAY K. & SUSAN E.","1853 FOX CHASE DR, GOODLETTSVILLE, TN",2.6,GENERAL SERVICES DISTRICT,50000.0,147300.0,197300.0,1985.0,3.0,3.0,0.0
4,22714,007 00 0 149.00,SINGLE FAMILY,"1829 FOX CHASE DR, GOODLETTSVILLE",2014-10-10,278000,20141015-0095255,No,"POST, CHRISTOPHER M. & SAMANTHA C.","1829 FOX CHASE DR, GOODLETTSVILLE, TN",2.0,GENERAL SERVICES DISTRICT,50000.0,152300.0,202300.0,1984.0,4.0,3.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56472,30469,188 10 0A 101.00,SINGLE FAMILY,"1435 WINDING CREEK DR, NOLENSVILLE",2015-05-27,157500,20150608-0053286,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56473,27707,188 10 0A 107.00,SINGLE FAMILY,"1423 WINDING CREEK DR, NOLENSVILLE",2015-03-02,145000,20150304-0019013,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56474,52709,188 10 0A 118.00,VACANT RESIDENTIAL LAND,"1804 GRACE POINT LN, NOLENSVILLE",2016-08-16,234611,20160819-0087214,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56475,54042,188 10 0A 121.00,VACANT RESIDENTIAL LAND,"1709 PARK TERRACE LN, NOLENSVILLE",2016-09-07,93844,20160919-0098411,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56476,54043,188 10 0A 122.00,VACANT RESIDENTIAL LAND,"1713 PARK TERRACE LN, NOLENSVILLE",2016-09-07,93844,20160919-0098411,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df['LandUse'].unique()

array(['SINGLE FAMILY', 'RESIDENTIAL CONDO', 'VACANT RURAL LAND',
       'VACANT RESIDENTIAL LAND', 'DUPLEX', 'CHURCH', 'ZERO LOT LINE',
       'RESIDENTIAL COMBO/MISC', 'PARSONAGE', 'GREENBELT', 'MOBILE HOME',
       'PARKING LOT', 'CLUB/UNION HALL/LODGE', 'TRIPLEX',
       'VACANT ZONED MULTI FAMILY', 'SPLIT CLASS', 'CONDO', 'QUADPLEX',
       'LIGHT MANUFACTURING', 'FOREST', 'CONVENIENCE MARKET WITHOUT GAS',
       'DORMITORY/BOARDING HOUSE', 'DAY CARE CENTER',
       'METRO OTHER THAN OFC, SCHOOL,HOSP, OR PARK',
       'TERMINAL/DISTRIBUTION WAREHOUSE', 'NIGHTCLUB/LOUNGE',
       'RESTURANT/CAFETERIA', 'VACANT COMMERCIAL LAND',
       'CONDOMINIUM OFC  OR OTHER COM CONDO', 'STRIP SHOPPING CENTER',
       'VACANT RESIENTIAL LAND', 'APARTMENT: LOW RISE (BUILT SINCE 1960)',
       'ONE STORY GENERAL RETAIL STORE', 'NON-PROFIT CHARITABLE SERVICE',
       'SMALL SERVICE SHOP', 'MORTUARY/CEMETERY'], dtype=object)

In [ ]:
df['LandUse'].str.contains()

In [97]:
pd.set_option('display.max.row', 20)

In [98]:
df

,UniqueID,ParcelID,LandUse,PropertyAddress,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerAddress,Acreage,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath
0,2045,007 00 0 125.00,SINGLE FAMILY,"1808 FOX CHASE DR, GOODLETTSVILLE",2013-04-09,240000,20130412-0036474,No,"FRAZIER, CYRENTHA LYNETTE","1808 FOX CHASE DR, GOODLETTSVILLE, TN",2.3,GENERAL SERVICES DISTRICT,50000.0,168200.0,235700.0,1986.0,3.0,3.0,0.0
1,16918,007 00 0 130.00,SINGLE FAMILY,"1832 FOX CHASE DR, GOODLETTSVILLE",2014-06-10,366000,20140619-0053768,No,"BONER, CHARLES & LESLIE","1832 FOX CHASE DR, GOODLETTSVILLE, TN",3.5,GENERAL SERVICES DISTRICT,50000.0,264100.0,319000.0,1998.0,3.0,3.0,2.0
2,54582,007 00 0 138.00,SINGLE FAMILY,"1864 FOX CHASE DR, GOODLETTSVILLE",2016-09-26,435000,20160927-0101718,No,"WILSON, JAMES E. & JOANNE","1864 FOX CHASE DR, GOODLETTSVILLE, TN",2.9,GENERAL SERVICES DISTRICT,50000.0,216200.0,298000.0,1987.0,4.0,3.0,0.0
3,43070,007 00 0 143.00,SINGLE FAMILY,"1853 FOX CHASE DR, GOODLETTSVILLE",2016-01-29,255000,20160129-0008913,No,"BAKER, JAY K. & SUSAN E.","1853 FOX CHASE DR, GOODLETTSVILLE, TN",2.6,GENERAL SERVICES DISTRICT,50000.0,147300.0,197300.0,1985.0,3.0,3.0,0.0
4,22714,007 00 0 149.00,SINGLE FAMILY,"1829 FOX CHASE DR, GOODLETTSVILLE",2014-10-10,278000,20141015-0095255,No,"POST, CHRISTOPHER M. & SAMANTHA C.","1829 FOX CHASE DR, GOODLETTSVILLE, TN",2.0,GENERAL SERVICES DISTRICT,50000.0,152300.0,202300.0,1984.0,4.0,3.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56472,30469,188 10 0A 101.00,SINGLE FAMILY,"1435 WINDING CREEK DR, NOLENSVILLE",2015-05-27,157500,20150608-0053286,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56473,27707,188 10 0A 107.00,SINGLE FAMILY,"1423 WINDING CREEK DR, NOLENSVILLE",2015-03-02,145000,20150304-0019013,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56474,52709,188 10 0A 118.00,VACANT RESIDENTIAL LAND,"1804 GRACE POINT LN, NOLENSVILLE",2016-08-16,234611,20160819-0087214,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56475,54042,188 10 0A 121.00,VACANT RESIDENTIAL LAND,"1709 PARK TERRACE LN, NOLENSVILLE",2016-09-07,93844,20160919-0098411,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56476,54043,188 10 0A 122.00,VACANT RESIDENTIAL LAND,"1713 PARK TERRACE LN, NOLENSVILLE",2016-09-07,93844,20160919-0098411,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
df.describe()

,SalePrice,Acreage,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath
count,2.120000e+02,13.000000,13.000000,13.000000,13.000000,5.000000,5.000000,5.000000,5.000000
mean,1.310445e+06,18.900769,61970.538462,63269.230769,142293.615385,1946.600000,3.400000,1.800000,0.200000
std,1.752724e+06,20.467634,52370.157336,168505.530990,216866.207700,29.971653,1.140175,1.788854,0.447214
min,1.400000e+04,1.280000,2195.000000,0.000000,2195.000000,1918.000000,2.000000,1.000000,0.000000
25%,1.787500e+05,5.450000,11024.000000,0.000000,12819.000000,1925.000000,3.000000,1.000000,0.000000
50%,3.072675e+05,7.750000,58320.000000,0.000000,105000.000000,1935.000000,3.000000,1.000000,0.000000
75%,4.062500e+06,27.820000,99195.000000,40000.000000,128200.000000,1966.000000,4.000000,1.000000,0.000000
max,4.250000e+06,68.790000,167919.000000,617000.000000,824070.000000,1989.000000,5.000000,5.000000,1.000000

In [29]:
df

,LandUse,PropertyAddress,SaleDate,SalePrice,SoldAsVacant,OwnerName,OwnerAddress,Acreage,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath
0,GREENBELT/RES_x000D_\nGRRENBELT/RES,"144 SCENIC VIEW RD, OLD HICKORY",2016-06-24,499900,No,"REEVES, TERRY C. & DIANE D.","144 SCENIC VIEW RD, OLD HICKORY, TN",47.50,GENERAL SERVICES DISTRICT,99195.0,32100.0,149495.0,1918.0,2.0,1.0,0.0
1,GREENBELT/RES_x000D_\nGRRENBELT/RES,"142 SCENIC VIEW RD, OLD HICKORY",2016-06-24,499900,No,"REEVES, TERRY C. & DIANE D.","142 SCENIC VIEW RD, OLD HICKORY, TN",1.28,GENERAL SERVICES DISTRICT,2195.0,0.0,2195.0,NaN,NaN,NaN,NaN
2,CONDO,"724 DUE WEST AVE N, MADISON",2014-05-15,82000,No,NaN,NaN,NaN,GENERAL SERVICES DISTRICT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CONDO,"428 B E PALESTINE AVE, MADISON",2013-08-12,72000,No,NaN,NaN,NaN,URBAN SERVICES DISTRICT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,GREENBELT,"1833 HUDSON RD, MADISON",2013-12-27,309535,No,"MANNING, DAVID W. & BETSY B.","1831 HUDSON RD, MADISON, TN",7.46,GENERAL SERVICES DISTRICT,9933.0,0.0,9933.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,CONDOMINIUM OFC OR OTHER COM CONDO,"6901 LENOX VILLAGE DR, NASHVILLE",2015-12-21,4000000,No,NaN,NaN,NaN,GENERAL SERVICES DISTRICT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
291,CONDOMINIUM OFC OR OTHER COM CONDO,"6971 SUNNYWOOD DR, NASHVILLE",2015-10-08,180000,No,NaN,NaN,NaN,GENERAL SERVICES DISTRICT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
292,CONDOMINIUM OFC OR OTHER COM CONDO,"6965 SUNNYWOOD DR, NASHVILLE",2016-08-26,160000,No,NaN,NaN,NaN,GENERAL SERVICES DISTRICT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293,CONDO,"8121 LENOX CREEKSIDE DR, ANTIOCH",2013-06-11,147500,No,NaN,NaN,NaN,GENERAL SERVICES DISTRICT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
294,CONDO,"8121 LENOX CREEKSIDE DR, ANTIOCH",2014-03-05,156000,No,NaN,NaN,NaN,GENERAL SERVICES DISTRICT,NaN,NaN,NaN,NaN,NaN,NaN,NaN